# Generated by Django 3.2 on 2021-05-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '태그', 'verbose_name_plural': '태그'},
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag table',
        ),
    ]
