# Generated by Django 3.2 on 2021-05-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_proxy',
            new_name='Usert',
        ),
        migrations.AlterModelOptions(
            name='usert',
            options={'verbose_name': '사용자 테이블', 'verbose_name_plural': '사용자 테이블'},
        ),
        migrations.AlterModelTable(
            name='usert',
            table='usert',
        ),
    ]
